apiVersion: v1
kind: Service
metadata:
  name: ecgo
spec:
  selector:
    app: ecgo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecgo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecgo
  template:
    metadata:
      labels:
        app: ecgo
    spec:
      containers:
      - name: ecgo
        image: registry:5000/ecgo:0.1.0
        ports:
        - containerPort: 8000
          name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecgo
spec:
  rules:
  - host: ecgo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ecgo
          servicePort: http
